Null correction for allowing multiple operations
preprocessy/preprocessy pull request #101
Opened 2021-08-15 04:52 UTC by Priyesh1202

This PR is a fix for the issue 100. It updates the code such that multiple null values handling operations can take place . 

https://github.com/preprocessy/preprocessy/issues/100

- Fixed #100 

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest`, no tests failed.

2021-08-15 11:49 UTC, Saif807380 requested changes

2021-08-15 11:49 UTC, Saif807380 commented on tests/test_null.py
> +#         handler.execute(params=test_input)
can be removed

2021-08-15 13:01 UTC, Parth576 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
It won't work like that. The columns given in ```fill_missing``` can be filled by either mean or median.

2021-08-15 13:03 UTC, Priyesh1202 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
You want me to add for that too? I can do that actually won't be too much of a change. Just a few changes here and there. 
Proposed solution: format: [method,col_list,..] so if col A -> mean and col B-> median then ["mean","col A","median","col B"]. So ill check for the keywords(mean/median) and will take the element next to the keyword match to extract its col_list. Will this be alright?

2021-08-15 13:11 UTC, Parth576 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
If there are many columns and the user wants to fill them with mean - ```["mean", "col A", "mean", "col B", "mean", "col 2"]```. Does not look that intuitive.

2021-08-15 13:38 UTC, Priyesh1202 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
cols will be list sorry

2021-08-15 13:40 UTC, Priyesh1202 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
So like the parameter can be of max length 4.. like [method, col list to apply, method, col list to apply]

2021-08-15 14:03 UTC, Parth576 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
Won't a dictionary be better than this so we can easily check the key? 
Example 1 - mean and median ```{ 'mean' : ['col A', 'col B'], 'median' : ['col C'] }```
Example 2 - only mean ```{ 'mean' : ['col A', 'col B'] }```

2021-08-15 14:16 UTC, Saif807380 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
A dictionary will be a good option. Or we can just have a list of lists, where the 0th index is for list of cols to be filled by mean and the next index is list of cols to filled by median.

2021-08-15 15:31 UTC, Priyesh1202 commented on docs/parameters.rst
> +- fill_missing(``list``): List with the format [[columns that the method will be applied on], method]. For example: [["Age"],"mean"].
List of list will be problematic is only median is required.. Ill make it a dictionary then..

2021-08-16 14:11 UTC, Saif807380 approved these changes
The code in `__validate_input()` has become too complicated now. Most of it just type checks across all modules. We should look into type safety options in python to simplify all of it.

2021-08-16 15:20 UTC, merged